LOCAL_PATH := $(call my-dir)

# Ramdisk is required to build kernel
TARGET_KERNEL_BINARIES : $(recovery_ramdisk) $(INSTALLED_RAMDISK_TARGET)

$(INSTALLED_BOOTIMAGE_TARGET): $(INSTALLED_KERNEL_TARGET) | $(ACP)
	$(call pretty,"Boot image: $@")
	$(ACP) $(INSTALLED_KERNEL_TARGET) $@

$(INSTALLED_RECOVERYIMAGE_TARGET): $(INSTALLED_BOOTIMAGE_TARGET)
	$(ACP) $(INSTALLED_BOOTIMAGE_TARGET) $@
